/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dstk.practice.java.linkedlist;

import java.util.ArrayList;

public class App {
	public String getGreeting() {
		return "Hello World, Practice Java Linked List!";
	}

	public static void main(String[] args) {
		System.out.println(new App().getGreeting());

		// Single LinkedList
		SingleLinkedListNode sllNode = new SingleLinkedListNode("1st node", null);
//		SingleLinkedList slList = null; // This will cause null exception
		SingleLinkedList slList = new SingleLinkedList();
		slList.setHead(sllNode);
		System.out.println("Single linked list first node (head.next) is: " + slList.getHead().getNext().getData());

		// Init list with String array
		ArrayList<String> initArray = new ArrayList<>();
		initArray.add("Hello!");
		initArray.add("Hi!");
		initArray.add("Hey!");
		initArray.add("Hej!");
		initArray.add("Halo!");
		initArray.add("哈喽!");
		initArray.add("Hii!");

		SingleLinkedList linitArray = new SingleLinkedList();
		linitArray.initWithArray(initArray);
		
		// Append the new String array
		ArrayList<String> appendArray = new ArrayList<>();
		appendArray.add("Welcome!");
		appendArray.add("欢迎!");
		appendArray.add("Leihou!");
		
		linitArray.appendArray(appendArray);

	}
}