/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dstk.practice.java.app;

import com.dstk.practice.java.maths.MathsUtil;
import com.dstk.practice.java.sort.IntegerArraySorter;

public class App {
	public String getGreeting() {
		return "Hello World from Algorithm Sorting\n";
	}

	public static void main(String[] args) throws Exception {
		System.out.println(new App().getGreeting());

		System.out.println("----------- Bubble Sorting -----------");
		int[] bArray = { 13, 14, 94, 33, 82, 25, 59, 94, 65, 23, 45, 27, 73, 25, 39, 10 };
		System.out.println(java.util.Arrays.toString(IntegerArraySorter.bubbleSort(bArray)));

		System.out.println("----------- Insertion Sorting -----------");
		int[] iArray = { 13, 14, 94, 33, 82, 25, 59, 94, 65, 23, 45, 27, 73, 25, 39, 10 };
		System.out.println(java.util.Arrays.toString(IntegerArraySorter.insertionSort(iArray)));
		
		System.out.println("----------- Shell Sorting -----------");
		int[] shellArray = { 13, 14, 94, 33, 82, 25, 59, 94, 65, 23, 45, 27, 73, 25, 39, 10, 1, 22, 2 };
		System.out.println(java.util.Arrays.toString(IntegerArraySorter.quickSort(shellArray)));

		System.out.println("----------- Selection Sorting -----------");
		int[] sArray = { 13, 14, 94, 33, 82, 25, 59, 94, 65, 23, 45, 27, 73, 25, 39, 10 };
		System.out.println(java.util.Arrays.toString(IntegerArraySorter.selectionSort(sArray)));

		System.out.println("----------- Merge Sorting -----------");
		int[] mArray = { 13, 14, 94, 33, 82, 25, 59, 94, 65, 23, 45, 27, 73, 25, 39, 10, 1 };
		System.out.println(java.util.Arrays.toString(IntegerArraySorter.mergeSort(mArray)));

		System.out.println("----------- Quick Sorting -----------");
		int[] qArray = { 13, 14, 94, 33, 82, 25, 59, 94, 65, 23, 45, 27, 73, 25, 39, 10, 1, 22 };
		System.out.println(java.util.Arrays.toString(IntegerArraySorter.quickSort(qArray)));
		
		System.out.println("----------- Quick Sorting application, find Nth largest item -----------");
		int[] qaArray = { 13, 14, 94, 33, 82, 25, 59, 94, 65, 23, 45, 27, 73, 25, 39, 10, 1, 22 };
		System.out.println(java.util.Arrays.toString(IntegerArraySorter.getNthLargestItem(qaArray, 3)));
		System.out.println(String.format("The %dth largest number is: '%d'", 3, IntegerArraySorter.getNthLargestItem(qaArray, 3)[2]));

		System.out.println("----------- Square root - Dichotomy -----------");
		System.out.println(String.format("%,.2f's square root is: '%,.2f'", 2.0, MathsUtil.SquareRoot1(2, 0.1)));
		System.out.println(String.format("The int value of %,.2f's square root is: '%d'", 2.0, Math.round(MathsUtil.SquareRoot1(2, 0.1))));

		System.out.println("----------- Square root - Newton method -----------");
		System.out.println(String.format("%,.2f's square root is: '%,.2f'", 2.0, MathsUtil.SquareRoot2(2, 0.1)));
		System.out.println(String.format("The int value of %,.2f's square root is: '%d'", 2.0, Math.round(MathsUtil.SquareRoot2(2, 0.1))));
		
	}
}
