/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dstk.practice.java.sort;

import org.testng.annotations.*;

import com.dstk.practice.java.app.App;

import static org.testng.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
